server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
          - id: identity-service
            uri: http://identity-service:8080
            predicates:
              - Path=/api/v1/auth/**, /api/v1/accounts/**, /api/v1/users/**
            filters:
              - AuthenticationFilter
          - id: fleet-service
            uri: http://fleet-service:8080
            predicates:
              - Path=/api/v1/fleets/**, /api/v1/vehicles/**, /api/v1/drivers/**
            filters:
              - AuthenticationFilter
          - id: wallet-service
            uri: http://wallet-service:8080
            predicates:
              - Path=/api/v1/wallets/**, /api/v1/transactions/**
            filters:
              - AuthenticationFilter
          - id: contract-service
            uri: http://contract-service:8080
            predicates:
              - Path=/api/v1/contracts/**
            filters:
              - AuthenticationFilter
          - id: bidding-service
            uri: http://bidding-service:3001
            predicates:
              - Path=/api/v1/bids/**, /bidding-socket/**
            filters:
              - AuthenticationFilter
          # Catch-all: mọi request không khớp API sẽ được chuyển đến Web Portal
          - id: web-portal
            uri: http://web-portal:3000
            predicates:
              - Path=/**

app:
  jwt:
    secret: ${APP_JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

eureka:
  client:
    enabled: false
